In [4]:
import pgl

In [1]:
import torch
torch.load('/data/zhaohuanjing/mag/dataset_path/pyg/planetoid/cora/processed/data.pt')

/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708]),
 None)

In [18]:
from inspect import stack
import torch as th
aa = th.tensor([[1,2,3],[4,5,6]])
aa.flatten()

# aa.view(6

tensor([1, 2, 3, 4, 5, 6])

In [2]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [3]:
import tqdm
with tqdm.trange(0,100, 20) as tq: #几列几列的取features
    for start in tq:
        print(start)

100%|██████████| 5/5 [00:00<00:00, 47021.35it/s]

0
20
40
60
80


In [1]:
import torch 
aa = torch.tensor([-1,0,1,-1,-1])
aa[aa>=0]

/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([0, 1])

In [14]:
import torch as th
import dgl
graph_data = {
   ('A', 'AP', 'P'): (th.tensor([0, 0, 1, 1, 2, 2, 3]), th.tensor([0, 2, 1, 4, 5, 1, 3])),
   ('P', 'PA', 'A'): (th.tensor([0, 2, 1, 4, 5, 1, 3]), th.tensor([0, 0, 1, 1, 2, 2, 3])),
   ('A', 'AI', 'I'): (th.tensor([0, 1]), th.tensor([0, 1])),
   ('I', 'IA', 'A'): (th.tensor([0, 1]), th.tensor([0, 1])),
   ('P', 'PP1', 'P'): (th.tensor([0, 0, 1]), th.tensor([1, 2, 2])),
   ('P', 'PP2', 'P'): (th.tensor([1, 2, 2]), th.tensor([0, 0, 1]))
}
g = dgl.heterograph(graph_data)
traces, _ = dgl.sampling.random_walk(g, [0, 0, 0, 1, 1, 1], metapath=[('A', 'AP', 'P')])
print(traces)
traces = traces[traces[:, 0] != traces[:, -1]]
print(traces)
# traces[:, 0] != traces[:, -1]

tensor([[0, 2],
        [0, 2],
        [0, 2],
        [1, 4],
        [1, 1],
        [1, 4]])
tensor([[0, 2],
        [0, 2],
        [0, 2],
        [1, 4],
        [1, 4]])


In [15]:
for sid, *_, did in traces.numpy():
    print(sid, did)

0 2
0 2
0 2
1 4
1 4


In [19]:
import numpy as np
m = {1:[1,2,3], 2:[4,5,6]}
mapper = {i: np.array(j) for i, j in m.items()}
print(mapper)

{1: array([1, 2, 3]), 2: array([4, 5, 6])}


In [23]:
import numpy as np
aa = np.zeros([2,4])
aa[1,:] = 2
aa

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.]])