In [4]:
import pgl

In [1]:
import torch
torch.load('/data/zhaohuanjing/mag/dataset_path/pyg/planetoid/cora/processed/data.pt')

/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708]),
 None)

In [18]:
from inspect import stack
import torch as th
aa = th.tensor([[1,2,3],[4,5,6]])
aa.flatten()

# aa.view(6

tensor([1, 2, 3, 4, 5, 6])

In [2]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [3]:
import tqdm
with tqdm.trange(0,100, 20) as tq: #几列几列的取features
    for start in tq:
        print(start)

100%|██████████| 5/5 [00:00<00:00, 47021.35it/s]

0
20
40
60
80


In [1]:
import torch 
aa = torch.tensor([-1,0,1,-1,-1])
aa[aa>=0]

/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([0, 1])

In [10]:
import torch as th
import dgl
graph_data = {
   ('A', 'AP', 'P'): (th.tensor([0, 0, 1, 1, 2, 2, 3]), th.tensor([0, 2, 1, 4, 5, 1, 3])),
   ('P', 'PA', 'A'): (th.tensor([0, 2, 1, 4, 5, 1, 3]), th.tensor([0, 0, 1, 1, 2, 2, 3])),
   ('A', 'AI', 'I'): (th.tensor([0, 1]), th.tensor([0, 1])),
   ('I', 'IA', 'A'): (th.tensor([0, 1]), th.tensor([0, 1])),
   ('P', 'PP1', 'P'): (th.tensor([0, 0, 1]), th.tensor([1, 2, 2])),
   ('P', 'PP2', 'P'): (th.tensor([1, 2, 2]), th.tensor([0, 0, 1]))
}
g = dgl.heterograph(graph_data)
traces, _ = dgl.sampling.random_walk(g, [0, 0, 0, 1, 1, 1], metapath=[('A', 'AP', 'P')])
print(traces)
traces = traces[traces[:, 0] != traces[:, -1]]
print(traces)
# traces[:, 0] != traces[:, -1]

tensor([[0, 2],
        [0, 2],
        [0, 0],
        [1, 4],
        [1, 1],
        [1, 4]])
tensor([[0, 2],
        [0, 2],
        [1, 4],
        [1, 4]])


In [11]:
g.out_edges([0,1], form='uv', etype=('P', 'PA', 'A'))

(tensor([0, 1, 1]), tensor([0, 1, 2]))

In [15]:
for sid, *_, did in traces.numpy():
    print(sid, did)

0 2
0 2
0 2
1 4
1 4


In [19]:
import numpy as np
m = {1:[1,2,3], 2:[4,5,6]}
mapper = {i: np.array(j) for i, j in m.items()}
print(mapper)

{1: array([1, 2, 3]), 2: array([4, 5, 6])}


In [23]:
import numpy as np
aa = np.zeros([2,4])
aa[1,:] = 2
aa

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [8]:
import torch
aa = torch.randn((5,2,3))
aa.flatten(1,-1).shape

torch.Size([5, 6])

In [5]:
import numpy as np
aa = np.array([1,2,3])
bb = np.array([4,5,6])
np.concatenate((aa,bb), axis=0)

array([1, 2, 3, 4, 5, 6])

In [7]:
def plus(aa):
    for ii in range(len(aa)):
        bb = aa[ii]
        bb+=1
    # return aa

aa = [1,2,3]

plus(aa)
print(aa)

[1, 2, 3]


In [22]:
import torch
aa = torch.Tensor([[1,2,3,4],[5,6,7,8]])
aa = torch.stack([aa,aa,aa],0)

print(aa.shape)
print(aa)
aa = aa.sum(dim=0)
print(aa)
aa/3

torch.Size([3, 2, 4])
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]],

        [[1., 2., 3., 4.],
         [5., 6., 7., 8.]],

        [[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
tensor([[ 3.,  6.,  9., 12.],
        [15., 18., 21., 24.]])


tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [107]:
import torch as th
import dgl
graph_data = {
   ('A', 'AP', 'P'): (th.tensor([0, 0, 1, 1, 2, 2, 3]), th.tensor([0, 2, 1, 4, 5, 1, 3])),
   ('P', 'PA', 'A'): (th.tensor([0, 2, 1, 4, 5, 1, 3]), th.tensor([0, 0, 1, 1, 2, 2, 3])),
   ('A', 'AI', 'I'): (th.tensor([0, 1]), th.tensor([0, 1])),
   ('I', 'IA', 'A'): (th.tensor([0, 1]), th.tensor([0, 1])),
   ('P', 'PP1', 'P'): (th.tensor([0, 0, 1]), th.tensor([1, 2, 2])),
   ('P', 'PP2', 'P'): (th.tensor([1, 2, 2]), th.tensor([0, 0, 1]))
}
g = dgl.heterograph(graph_data)
print(g['PP1'].edges())
print(g['PP2'].edges())
# print(dgl.metapath_reachable_graph(g, [('A', 'AP', 'P'), ('P', 'PA', 'A')]))
# print(g.edge_type_subgraph(['PP2']).edges())
g.edge_type_subgraph(['PP2'])


(tensor([0, 0, 1]), tensor([1, 2, 2]))
(tensor([1, 2, 2]), tensor([0, 0, 1]))


Graph(num_nodes=6, num_edges=3,
      ndata_schemes={}
      edata_schemes={})

In [41]:
g.in_degrees()

DGLError: Edge type name must be specified if there are more than one edge types.

In [94]:
import dgl
import torch
g = dgl.graph((torch.tensor([0,0,1,1,2,3]), torch.tensor([1,2,3,4,4,5])))

In [99]:
g.in_edges([4,5])

(tensor([1, 2, 3]), tensor([4, 4, 5]))

In [49]:
(1.0 / (g.in_degrees() + 1)).reshape([-1, 1])

tensor([[1.0000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.3333],
        [0.5000]])

In [51]:
g.num_nodes

<bound method DGLHeteroGraph.num_nodes of Graph(num_nodes=6, num_edges=6,
      ndata_schemes={}
      edata_schemes={})>

In [61]:
from ogb.lsc import MAG240MDataset
import numpy as np
dataset = MAG240MDataset(root="dataset_path")
node_ids = np.concatenate(
        [dataset.get_idx_split(c).astype(np.int64) for c in ['train', 'valid', 'test-whole']]
    ) # 有标签的那些papers
paper_label = dataset.all_paper_label
y_base = paper_label[node_ids]
# y_base = y_base[y_base>=0]
print(y_base.shape)

(1398159,)


In [63]:
y_base

array([17., 29., 38., ..., -1., -1., -1.])

In [84]:
import numpy as np
aa = np.array([-1,-1,0,-1,1,-1,2,3])
q = np.array([0,1,2,3])
# np.where(aa==q)
mask = np.where(aa>=0)
rr = np.zeros(4)
rr[np.arange(4)] = mask
print(rr)

[2. 4. 6. 7.]


In [92]:
aa = aa.astype("float32")
print(aa)

[-1. -1.  0. -1.  1. -1.  2.  3.]


In [106]:
import torch
aa = torch.tensor([2,4,1,3])
aa.unsqueeze(0).T

tensor([[2],
        [4],
        [1],
        [3]])

In [101]:
aa = [1,2,3,4]
bb = [5,6,7,8]
for x,y in zip(aa,bb):
    print(x,y)

1 5
2 6
3 7
4 8


In [108]:
import numpy as np
aa = np.array([10])
bb = np.array([False])
aa[bb]


array([], dtype=int64)

In [109]:
import numpy as np
import torch as th
aa = np.array([10])
bb = th.BoolTensor([False])
aa[bb]

10

In [110]:
import numpy as np
import torch as th
aa = th.tensor([10])
bb = th.BoolTensor([False])
aa[bb]

tensor([], dtype=torch.int64)

In [115]:
import numpy as np
aa = np.array([[1,2],[3,4],[5,6]])
aa.T

array([[1, 3, 5],
       [2, 4, 6]])

In [116]:
list(range(1, 5))

[1, 2, 3, 4]

In [3]:
aa = 1
bb = aa
aa += 1
print(bb,aa)

1 2


In [ ]:
aa+=