In [4]:
import torch

In [8]:
cc = torch.Tensor([1,2,3,4,5,6,7])
aa = torch.LongTensor([[0,2],[4,5]])
cc[aa[0][0]:aa[0][1]]

tensor([1., 2.])

In [16]:
aa = torch.arange(0,2)
bb = torch.arange(4,5)
torch.cat((aa,bb,aa))

tensor([0, 1, 4, 0, 1])

In [29]:
from curses import flash
import numpy as np
import random as rd
aa = np.array([1,2,3,4,5])
np.random.choice(aa, 3, replace=False)

array([1, 5, 2])

In [7]:

from torch_geometric.data import HeteroData
from torch_geometric.utils import subgraph
import scipy.sparse as sp
import numpy as np
data = HeteroData()
# ap_edges = torch.LongTensor([[0,1],[0,2],[1,0],[1,3],[1,4]])
ap_edges = torch.LongTensor([[0,0,1,1,1],[1,2,0,3,4]])
# data['a','writes','p'].edge_index = ap_edges
# subgraph(torch.LongTensor([0,1,3,4]), data['a','writes','p'].edge_index)[0]
csr = sp.csr_matrix((np.ones(5),(ap_edges[0], ap_edges[1])), shape=(2,5))
print(csr.indptr, csr.indices)

[0 2 5] [1 2 0 3 4]


In [2]:
from torch_geometric.data import HeteroData
from torch_geometric.utils import subgraph
from torch_geometric.utils import subgraph, bipartite_subgraph
import scipy.sparse as sp
import numpy as np
import torch
data = HeteroData()
# ap_edges = torch.LongTensor([[0,1],[0,2],[1,0],[1,3],[1,4]])
ap_edges = torch.LongTensor([[0,0,1,1,1],[1,2,0,3,4]])
vp_edges = torch.LongTensor([[0,0,1,2,1],[0,3,1,2,4]])
data['a','writes','p'].edge_index = ap_edges
data['v','publishes','p'].edge_index = ap_edges
data['a'].x = torch.Tensor([[0],[1]])
data['p'].x = torch.Tensor([[0],[1],[2],[3],[4]])
data['v'].x = torch.Tensor([[0],[1],[2]])
# subgraph(torch.LongTensor([0,1,3,4]), data['a','writes','p'].edge_index)[0]
subg = data.subgraph({'a':torch.LongTensor([1]), 'p':torch.LongTensor([3,4,2]), 'v':torch.LongTensor([0,1])})
bsybgap, _ = bipartite_subgraph((torch.tensor([1]), torch.tensor([3,4,2])), ap_edges, relabel_nodes=True)
bsybgvp, _ = bipartite_subgraph((torch.tensor([0,1]), torch.tensor([3,4,2])), ap_edges, relabel_nodes=True)
print(subg)
print(subg['a','writes','p']['edge_index'])
print(subg['v','publishes','p']['edge_index'])
print(bsybgap)
print(bsybgvp)
# print(subg['a'].x)
print(subg['p'].x)
# print(subg['v'].x)


HeteroData(
  a={ x=[1, 1] },
  p={ x=[3, 1] },
  v={ x=[2, 1] },
  (a, writes, p)={ edge_index=[2, 2] },
  (v, publishes, p)={ edge_index=[2, 3] }
)
tensor([[0, 0],
        [1, 2]])
tensor([[0, 1, 1],
        [0, 1, 2]])
tensor([[0, 0],
        [1, 2]])
tensor([[0, 1, 1],
        [0, 1, 2]])
tensor([[3.],
        [4.],
        [2.]])


In [18]:
print(subg)
print(subg[('a', 'writes', 'p')])
print(subg[('v', 'publishes', 'p')])
aa = subg.to_homogeneous()
print(aa)
from torch_geometric.utils import to_networkx
nxg = to_networkx(aa)
print(nxg)
# print(subg.to_homogeneous())
from torch_geometric.utils import subgraph, bipartite_subgraph
ap_edges = torch.LongTensor([[0,0,1,1,1],[1,2,0,3,4]])
bipartite_subgraph((torch.tensor([1]), torch.tensor([0,3,4])), ap_edges, return_edge_mask=True)

HeteroData(
  a={ x=[1, 1] },
  p={ x=[3, 1] },
  v={ x=[2, 1] },
  (a, writes, p)={ edge_index=[2, 2] },
  (v, publishes, p)={ edge_index=[2, 3] }
)
{'edge_index': tensor([[0, 0],
        [1, 2]])}
{'edge_index': tensor([[0, 1, 1],
        [0, 1, 2]])}
Data(edge_index=[2, 5], x=[6, 1], node_type=[6], edge_type=[5])
DiGraph with 6 nodes and 5 edges


In [37]:
subg['p'].x.shape[0]


3

In [50]:
ap_edges = torch.LongTensor([[0,0,1,1,1],[1,2,0,3,4]])
subgraph(torch.LongTensor([1,4]), ap_edges)

(tensor([[1],
         [4]]),
 None)

In [65]:
aa = torch.tensor([False, False,  True, False,  True])
bb = torch.tensor([False, False,  True, True,  True])
print(isinstance(aa, torch.BoolTensor))
aa & bb

True


tensor([False, False,  True, False,  True])

In [48]:
import torch
aa = torch.tensor([0, 0, 1, 0, 1])
bb = torch.tensor([0, 0, 1, 1 ,1])
# print(isinstance(aa, torch.BoolTensor))
aa & bb

tensor([0, 0, 1, 0, 1])

In [1]:
import numpy as np
x = np.memmap('/data/zhaohuanjing/mag/dataset_path/mag240m_kddcup2021/full_feat.npy', dtype=np.float16,
                      mode='r', shape=(244160499, 768))

In [4]:
import torch
aa = torch.from_numpy(x)

/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  


In [81]:
from torch_geometric.data import HeteroData
from torch_geometric.utils import subgraph
from torch_geometric.utils import subgraph, bipartite_subgraph
import scipy.sparse as sp
import numpy as np
import torch
data = HeteroData()
# ap_edges = torch.LongTensor([[0,1],[0,2],[1,0],[1,3],[1,4]])
ap_edges = torch.LongTensor([[0,0,1,1,1],[1,2,0,3,4]])
vp_edges = torch.LongTensor([[0,0,1,2,1],[0,3,1,2,4]])
data['a','writes','p'].edge_index = ap_edges
data['v','publishes','p'].edge_index = ap_edges
data['a'].x = torch.Tensor([[0],[1]])
data['p'].x = torch.Tensor([[0],[1],[2],[3],[4]])
data['v'].x = torch.Tensor([[0],[1],[2]])
# subgraph(torch.LongTensor([0,1,3,4]), data['a','writes','p'].edge_index)[0]
for node_type, store in data._node_store_dict.items():
    print(store.num_nodes)

2
5
3


In [9]:
aa = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
aa[2:3]

tensor([[7, 8, 9]])

In [31]:
aa = torch.tensor([[1],[2],[3],[4],[5],[6],[7],[8],[9]])
print(aa[torch.tensor([2,4])])
print(aa[torch.tensor([False, False, True, False, True, False, False, False, False])])

tensor([[3],
        [5]])
tensor([[3],
        [5]])


In [32]:
aa = torch.tensor([0,1,2,3])

In [40]:
import numpy as np
aa = np.array([[1,2,3],[4,5,6]])
np.concatenate((aa,aa,aa), axis=0)


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
import networkx

ModuleNotFoundError: No module named 'networkx'

In [51]:
import torch as th
# aa = th.tensor([1,2,3,2,4,5,2,3])
# th.numel(aa[aa<=2])
bb = th.tensor([True, False, False])
th.numel(bb[bb])

1

In [66]:
from tokenize import Double3
import torch as th
aa = th.tensor([Double(float('nan')), 1,1,2])
aa = th.unique(aa)
# print(aa)
isinstance(aa, torch.FloatTensor)

TypeError: 'str' object is not callable

In [74]:
import torch
aa = torch.tensor([0,1,2,3,4,5,6])
bb = [1,4]
print(aa[bb])
print(aa[~bb])

tensor([1, 4])


TypeError: bad operand type for unary ~: 'list'

In [75]:
import torch
torch.zeros(10, dtype=torch.long)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
np.array([], dtype=np.int64)

array([], dtype=int64)

In [89]:
import torch
aa = [torch.tensor([0,1,2,3,4,5,6])]
bb = [torch.tensor([2,3,4,5,6,7,8])]
aa += [aa,bb]
print(aa)
print(len(aa))
aa[1]

[tensor([0, 1, 2, 3, 4, 5, 6]), [...], [tensor([2, 3, 4, 5, 6, 7, 8])]]
3


[tensor([0, 1, 2, 3, 4, 5, 6]), [...], [tensor([2, 3, 4, 5, 6, 7, 8])]]

In [10]:
import torch

batch_size = 5
nb_digits = 10
# Dummy input that HAS to be 2D for the scatter (you can use view(-1,1) if needed)
y = torch.LongTensor([1,3,0,3,2])
y = y.unsqueeze(1)
print(y)
# One hot encoding buffer that you create out of the loop and just keep reusing
# y_onehot = torch.FloatTensor(batch_size, nb_digits)
# print(y_onehot)

# In your for loop
y_onehot = torch.zeros(5, 4)
print(y_onehot)
y_onehot.scatter_(1, y, 1)
print(y_onehot)

y_onehot = torch.zeros(batch_size, nb_digits).scatter_(1, y, 1)
print(y_onehot)

tensor([[1],
        [3],
        [0],
        [3],
        [2]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])
tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])


In [1]:
import torch
from torch_sparse import SparseTensor, sample, sample_adj
row = torch.tensor([0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 4, 4, 5, 5])
col = torch.tensor([1, 2, 3, 0, 2, 0, 1, 4, 5, 0, 2, 5, 2, 4])
value = torch.arange(row.size(0))
adj_t = SparseTensor(row=row, col=col, value=value, sparse_sizes=(6, 6))

/home/zhaohuanjing/anaconda3/envs/th19cu111/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
adj_t.coo()

(tensor([0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 4, 4, 5, 5]),
 tensor([1, 2, 3, 0, 2, 0, 1, 4, 5, 0, 2, 5, 2, 4]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]))